# Site settings
title: "Ahtasham Anjum | Data Analyst"
email: "ahtashamd321@gmail.com"
description: >-
  I'm a data analyst passionate about turning raw data into meaningful insights using Python, SQL, Excel, and Power BI. I help organizations make better, data-driven decisions through analytics and visualization.

twitter_username: ""
github_username: ahtashamd321
minimal_mistakes_skin: dark  # you can also try: default, air, neon, dirt, sunrise
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Asia/Kolkata

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ahtasham Anjum"
  avatar : "/assets/images/anjum.jpg"  # replace this with your photo file name later
  bio    : "Certified Data Analyst skilled in Python, SQL, Power BI, and Excel. Passionate about data storytelling and transforming numbers into insights."
  links:
    - label: "Portfolio"
      icon: "fas fa-fw fa-link"
      url: "https://ahtashamd321.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ahtashamd321"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ahtasham-anjum/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ahtashamd321@gmail.com"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ahtashamd321"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: https://www.linkedin.com/in/ahtasham-anjum
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ahtashamd321@gmail.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
